version: "3"
services:
  auth_api_service:
    container_name: auth_api_service
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c  "alembic revision --autogenerate && alembic upgrade head && python main.py"
    ports:
      - "3005:3005"
      - "50051:50051"
    volumes:
      - ./:/code
    env_file:
      - .env

  auth_db_service:
    image: postgres:13
    restart: on-failure
    container_name: auth_db_service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_POST_AUTH_METHOD: trust
    expose:
      - 5433
    env_file:
      - .env
